name: Bug report 
description: Report a bug about the client
labels: bug
body:
  - type: input
    attributes:
        label: Description
        description: A clear and concise description of what the bug is.
  - type: input
    attributes:
        label: Steps 
        description: Steps to reproduce the behavior.
    validations:
        required: true




