name: Bug report 
description: Report a bug about the client
labels: bug
body:
  - type: input
    attributes:
        label: Description
        description: A clear and concise description of what the bug is.
    validations:
        required: true
  - type: input
    attributes:
        label: Steps 
        description: Steps to reproduce the behavior.
    validations:
        required: true
  - type: input
    attributes:
        label: Expected behavior
        description: A clear and concise description of what you expected to happen. 
    validations: 
        required: true
  




